In [ ]:
import pandas as pd

train = pd.read_csv("/content/drive/MyDrive/ml_dataset/train.csv")
meal = pd.read_csv("/content/drive/MyDrive/ml_dataset/meal_info.csv")
center = pd.read_csv("/content/drive/MyDrive/ml_dataset/fulfilment_center_info.csv")

In [ ]:
train.head()
meal.head()
center.head()

   center_id  city_code  region_code center_type  op_area
0         11        679           56      TYPE_A      3.7
1         13        590           56      TYPE_B      6.7
2        124        590           56      TYPE_C      4.0
3         66        648           34      TYPE_A      4.1
4         94        632           34      TYPE_C      3.6

In [ ]:
data = train.merge(meal, on="meal_id")
data = data.merge(center, on="center_id")

In [ ]:
data.head()

,id,week,center_id,meal_id,checkout_price,base_price,emailer_for_promotion,homepage_featured,num_orders,category,cuisine,city_code,region_code,center_type,op_area
0,1379560,1,55,1885,136.83,152.29,0,0,177,Beverages,Thai,647,56,TYPE_C,2.0
1,1466964,1,55,1993,136.83,135.83,0,0,270,Beverages,Thai,647,56,TYPE_C,2.0
2,1346989,1,55,2539,134.86,135.86,0,0,189,Beverages,Thai,647,56,TYPE_C,2.0
3,1338232,1,55,2139,339.50,437.53,0,0,54,Beverages,Indian,647,56,TYPE_C,2.0
4,1448490,1,55,2631,243.50,242.50,0,0,40,Beverages,Indian,647,56,TYPE_C,2.0

In [ ]:
data.info()
data.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 456548 entries, 0 to 456547
Data columns (total 15 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   id                     456548 non-null  int64
 1   week                   456548 non-null  int64
 2   center_id              456548 non-null  int64
 3   meal_id                456548 non-null  int64
 4   checkout_price         456548 non-null  float64
 5   base_price             456548 non-null  float64
 6   emailer_for_promotion  456548 non-null  int64
 7   homepage_featured      456548 non-null  int64
 8   num_orders             456548 non-null  int64
 9   category               456548 non-null  object
 10  cuisine                456548 non-null  object
 11  city_code              456548 non-null  int64
 12  region_code            456548 non-null  int64
 13  center_type            456548 non-null  object
 14  op_area                456548 non-null  float64
dtypes: float64(3), int64(9), object(3)
memory usage: 52.2+ MB

id                       0
week                     0
center_id                0
meal_id                  0
checkout_price           0
base_price               0
emailer_for_promotion    0
homepage_featured        0
num_orders               0
category                 0
cuisine                  0
city_code                0
region_code              0
center_type              0
op_area                  0
dtype: int64

In [ ]:
data['demand'] = data['num_orders'].apply(lambda x: 1 if x > 100 else 0)

In [ ]:
data = data.drop(['num_orders'], axis=1)

In [ ]:
data = pd.get_dummies(data)

In [ ]:
from sklearn.model_selection import train_test_split

X = data.drop('demand', axis=1)
y = data['demand']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)